services:
  hugo:
    image: nginx:alpine
    container_name: hugo
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"

        # HTTPS Router
      - "traefik.http.routers.hugo-secure.rule=Host(`jorgesintes.xyz`) || Host(`www.jorgesintes.xyz`)"
      - "traefik.http.routers.hugo-secure.entrypoints=https"
      - "traefik.http.routers.hugo-secure.tls.certresolver=letsencrypt"
        # HTTP Router for Redirect
      - "traefik.http.routers.hugo.rule=Host(`jorgesintes.xyz`) || Host(`www.jorgesintes.xyz`)"
      - "traefik.http.routers.hugo.entrypoints=http"
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    external: true
