services:
  hugo:
    build: .
    container_name: jorgesintes_xyz
    labels:
      - "traefik.enable=true"

      # HTTPS Router
      - "traefik.http.routers.hugo-secure.rule=Host(`jorgesintes.xyz`) || Host(`www.jorgesintes.xyz`)"
      - "traefik.http.routers.hugo-secure.entrypoints=https"
      - "traefik.http.routers.hugo-secure.tls.certresolver=letsencrypt"

      # HTTP Router for Redirect
      - "traefik.http.routers.hugo.rule=Host(`jorgesintes.xyz`) || Host(`www.jorgesintes.xyz`)"
      - "traefik.http.routers.hugo.entrypoints=http"
      - "traefik.http.routers.hugo.middlewares=redirect-to-https"

      # Middleware Definition
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
